### ISSUE TITLE
HELP: Get last submission timing

### ISSUE THREAD

**Issue by charlieamer** [cms-dev/cms#1230] opened 2023-03-08 17:33 UTC
What would be the way to get the timestamp at which point a contestant reached final score ? I just need guidance to do it programatically, either by sql, python, json, or any other way.

For example, if contestant finished with score 180, I need timestamp at what point the participant reached that score, even if the contestant has later added submissions that wouldn't change his/her overall score.

Use case: If there are multiple contestants with same score, and we HAVE TO choose top 3, the easiest way to do it is to do it. Since we organize lots of competitions, we want to reduce human mistakes and do it programatically.

Please help !

**Comment by wil93** [comment] 2023-04-30 11:10
You could query this data directly via SQL (by using the tables `submissions`, `submissionresults`, `participations`, `users`, etc)

Another approach: some time ago I implemented a very rough support for "penalty" and "first to solve" features (ICPC-style). I implemented these in the RankingWebServer, so if you have an RWS instance you could restart it with this code instead and you should be able to see the penalty (it's calculated on the frontend): https://github.com/wil93/cms/tree/itacpc

Closing as it's not a bug (maybe it could be a feature request?)

**Closed by wil93** 2023-04-30 11:10 UTC
