### ISSUE TITLE
Updating a contest does not detach old users

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#903] opened 2018-03-18 13:30 UTC
**Description:**
If you import a contest with a set of user and then you update the contest with a different set of user in the end you will get a contest with all the user (the old and new ones enabled).

**Steps to reproduce:**
1. Create the following contest file `contest.yaml` in `italy_yaml` format (this is **`contest_1.yaml`**)
```yaml
nome_breve: testcontest
nome: "Test contest"

problemi:
  - testtask

# start: Monday, January 1, 2018 12:00:00 PM (GMT)
inizio: 1514808000
# end:  Friday, January 1, 2100 12:00:00 PM (GMT)
fine: 4102488000

utenti:
- username: 'u1'
  password: 'aaa'
- username: 'u2'
  password: 'bbb'
- username: 'u3'
  password: 'ccc'
- username: 'u4'
  password: 'ddd'
- username: 'u5'
  password: 'eee'
```

2. Import the users in CMS (`.` is the contest dir): 
```
$ cmsImportUser -L italy_yaml --all
2018-03-18 13:36:03,366 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
2018-03-18 13:36:03,675 - INFO [<unknown>] Loading parameters for contest testcontest.
2018-03-18 13:36:03,676 - WARNING [<unknown>] contest.yaml uses a deprecated format for token settings which will soon stop being supported, you're advised to update it.
2018-03-18 13:36:03,676 - INFO [<unknown>] Contest parameters loaded.
2018-03-18 13:36:03,677 - INFO [<unknown>] Loading parameters for user u1.
2018-03-18 13:36:03,679 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:36:03,680 - INFO [<unknown>] Creating user u1 on the database.
2018-03-18 13:36:03,703 - INFO [<unknown>] Import finished (new user id: 1).
2018-03-18 13:36:03,704 - INFO [<unknown>] Loading parameters for user u2.
2018-03-18 13:36:03,707 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:36:03,708 - INFO [<unknown>] Creating user u2 on the database.
2018-03-18 13:36:03,712 - INFO [<unknown>] Import finished (new user id: 2).
2018-03-18 13:36:03,713 - INFO [<unknown>] Loading parameters for user u3.
2018-03-18 13:36:03,715 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:36:03,715 - INFO [<unknown>] Creating user u3 on the database.
2018-03-18 13:36:03,719 - INFO [<unknown>] Import finished (new user id: 3).
2018-03-18 13:36:03,720 - INFO [<unknown>] Loading parameters for user u4.
2018-03-18 13:36:03,722 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:36:03,723 - INFO [<unknown>] Creating user u4 on the database.
2018-03-18 13:36:03,726 - INFO [<unknown>] Import finished (new user id: 4).
2018-03-18 13:36:03,727 - INFO [<unknown>] Loading parameters for user u5.
2018-03-18 13:36:03,730 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:36:03,730 - INFO [<unknown>] Creating user u5 on the database.
2018-03-18 13:36:03,735 - INFO [<unknown>] Import finished (new user id: 5).
```

3. Run (`.` is the contest dir): 
```
$ cmsImportContest -L italy_yaml .
2018-03-18 13:38:01,925 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
2018-03-18 13:38:02,248 - INFO [<unknown>] Loading parameters for contest testcontest.
2018-03-18 13:38:02,248 - WARNING [<unknown>] contest.yaml uses a deprecated format for token settings which will soon stop being supported, you're advised to update it.
2018-03-18 13:38:02,248 - INFO [<unknown>] Contest parameters loaded.
2018-03-18 13:38:02,304 - INFO [<unknown>] Creating contest on the database.
2018-03-18 13:38:02,309 - INFO [<unknown>] Import finished (new contest id: 2).
```

You will obtain the following:
![admin test contest - mozilla firefox_030](https://user-images.githubusercontent.com/367272/37566237-bc35325c-2ab6-11e8-8c42-c6a18a99bcde.png)

4. modify `contest.yaml` as follows (this is **`contest_2.yaml`**):
```yaml
nome_breve: testcontest
nome: "Test contest"

problemi:
  - testtask

# start: Monday, January 1, 2018 12:00:00 PM (GMT)
inizio: 1514808000
# end:  Friday, January 1, 2100 12:00:00 PM (GMT)
fine: 4102488000

utenti:
- username: 'u1'
  password: 'aaa'
- username: 'u6'
  password: 'fff'
- username: 'u7'
  password: 'ggg'
- username: 'u4'
  password: 'ddd'
- username: 'u8'
  password: 'hhh'
```

5. Import the new users (`.` is the contest dir):
```
$ cmsImportUser -L italy_yaml --all
2018-03-18 13:59:41,881 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
2018-03-18 13:59:42,209 - INFO [<unknown>] Loading parameters for contest testcontest.
2018-03-18 13:59:42,209 - WARNING [<unknown>] contest.yaml uses a deprecated format for token settings which will soon stop being supported, you're advised to update it.
2018-03-18 13:59:42,210 - INFO [<unknown>] Contest parameters loaded.
2018-03-18 13:59:42,211 - INFO [<unknown>] Loading parameters for user u1.
2018-03-18 13:59:42,213 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:59:42,213 - INFO [<unknown>] Creating user u1 on the database.
2018-03-18 13:59:42,226 - CRITICAL [<unknown>] The user already exists.
2018-03-18 13:59:42,226 - INFO [<unknown>] Loading parameters for user u6.
2018-03-18 13:59:42,229 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:59:42,229 - INFO [<unknown>] Creating user u6 on the database.
2018-03-18 13:59:42,234 - INFO [<unknown>] Import finished (new user id: 6).
2018-03-18 13:59:42,235 - INFO [<unknown>] Loading parameters for user u7.
2018-03-18 13:59:42,237 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:59:42,238 - INFO [<unknown>] Creating user u7 on the database.
2018-03-18 13:59:42,247 - INFO [<unknown>] Import finished (new user id: 7).
2018-03-18 13:59:42,247 - INFO [<unknown>] Loading parameters for user u4.
2018-03-18 13:59:42,250 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:59:42,250 - INFO [<unknown>] Creating user u4 on the database.
2018-03-18 13:59:42,252 - CRITICAL [<unknown>] The user already exists.
2018-03-18 13:59:42,253 - INFO [<unknown>] Loading parameters for user u8.
2018-03-18 13:59:42,255 - INFO [<unknown>] User parameters loaded.
2018-03-18 13:59:42,256 - INFO [<unknown>] Creating user u8 on the database.
2018-03-18 13:59:42,260 - INFO [<unknown>] Import finished (new user id: 8).
```

6. Update the contest:
```
$ cmsImportContest -L italy_yaml -u .
2018-03-18 13:59:48,912 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
2018-03-18 13:59:49,242 - INFO [<unknown>] Loading parameters for contest testcontest.
2018-03-18 13:59:49,243 - WARNING [<unknown>] contest.yaml uses a deprecated format for token settings which will soon stop being supported, you're advised to update it.
2018-03-18 13:59:49,243 - INFO [<unknown>] Contest parameters loaded.
2018-03-18 13:59:49,265 - WARNING [<unknown>] Participation of user u1 in this contest already exists, not going to update it.
2018-03-18 13:59:49,285 - WARNING [<unknown>] Participation of user u4 in this contest already exists, not going to update it.
2018-03-18 13:59:49,292 - INFO [<unknown>] Import finished (new contest id: 2).
```

You will obtain the following:
![admin test contest - mozilla firefox_031](https://user-images.githubusercontent.com/367272/37566293-69a82d2c-2ab7-11e8-848d-4f6be04667d4.png)

**Expected:** [What should have happened?]
The contest should have contained only the users specified in `contest_2.yaml` - that is `u1`, `u6`,`u7`,`u4` and `u8` - with the other used detached from the contest (detached, not removed)

**Actual:** [What happened instead?]
All the users `u1`-`u8` are attached to the contest.

### Logs
The output of each command is above.

### System Information

**CMS version:** `1.3.0
**Was CMS installed:** yes
**Using a virtualenv:** no
**Postgres version:** 9.5
**Distribution and version:** Ubuntu 16.04.4 LTS (xenial)

**Comment by stefano-maggiolo** [comment] 2018-03-18 18:32
Hi Cristian, this behaviour was intended when we fixed that other bug that caused submissions to be cleared.

The rationale for not removing participation was that submissions are attached to participations, so if you clear them you remove also the submissions (and that looked dangerous). I guess we could add a flag "I know what I'm doing", but I'm afraid this is outside the scope for a 1.3.1.

**Comment by CristianCantoro** [comment] 2018-03-18 22:45
It looks to me this is a different thing, The users should only be detached from the contest, not removed altogether.

**Comment by stefano-maggiolo** [comment] 2018-03-18 22:59
Sadly a submission cannot live without a participation. Removing a user
from the contest means deleting the participation, that in turns would
delete the dependant submission.

**Comment by CristianCantoro** [comment] 2018-03-18 23:30
Ok, another question could be. Is there a way to remove users from a contest in bulk without removing them from the DB? If I use `cmsRemoveUser` it eliminates the user from all contest, whereas if I use the admin interface I remove it only from the current contest, if I am correct.

**Comment by lerks** [comment] 2018-03-18 23:31
Look at `RemoveParticipation`, it should do what you are asking for

**Comment by CristianCantoro** [comment] 2018-03-18 23:53
Thanks @lerks, that is what I was looking for. One question, if I use `cmsRemoveParticipation` to remove a user's participation in a contest I will lose the submission that user has made to that contest or not?

**Comment by lerks** [comment] 2018-03-19 00:05
Yes, you will lose all submissions (and tokens, and tests, and questions, etc.).

**Comment by CristianCantoro** [comment] 2018-03-19 00:12
@lerks, perfect;y clear, thanks.

**Comment by lerks** [comment] 2018-03-19 08:40
No problem, I am closing this as the issue seems to have been resolved.

**Closed by lerks** 2018-03-19 08:40 UTC

**Comment by stefano-maggiolo** [comment] 2018-03-22 08:46
There is now a flag to do this in master (future 1.4)
