### ISSUE TITLE
RWS: if a user/task is removed from the contest, it will stay on RWS anyway

### ISSUE THREAD

**Issue by wil93** [cms-dev/cms#488] opened 2015-10-22 17:05 UTC
If a user was (by mistake) not hidden, and ProxyService has already sent out the user/task lists to a RWS instance, there is no way to make RWS delete the data (apart from `cmsRankingWebServer -d`). The same seems to happen when you delete the task/user.

The expected behavior is: RWS should notice that (if ProxyService sends the users/tasks again) some users or tasks could be missing, so the corresponding rows/columns should be deleted.

**Comment by lerks** [comment] 2016-06-17 12:21
I agree that the protocol that PS uses to communicate with RWS should be modified to keep data better in sync. Proposals are welcome.

I just wanted to point out that anyway the admin intervention in such cases should be minimal, if they use the proper tool: `cmsRWSHelper`. In this case the command would be `cmsRWSHelper delete user <username>`. No downtime and no `--drop` needed. Piece of cake.

**Comment by wil93** [comment] 2016-06-17 15:31
Cool, I didn't know about `cmsRWSHelper` :+1:

**Comment by lerks** [comment] 2017-04-06 14:44
I think this is effectively a duplicate of #107.

**Closed by lerks** 2017-04-06 14:44 UTC
Labels: feature_request, ps, rws

**Comment by wil93** [comment] 2017-04-06 15:18
Maybe it makes sense to add the labels (ps and rws) to the other issue as well.
