### ISSUE TITLE
Adding multiple test cases from a zip file to a task is not working

### ISSUE THREAD

**Issue by ashikoff** [cms-dev/cms#893] opened 2018-03-14 08:45 UTC
Hello there,
I've updated my 1.3 cms installation , dropped and initialized the database. At start all was ok, but when I tried to upload multiple testcases in my task I got an error:

Testcase.__init__() got a '<type 'str'>' for keyword argument 'codename', which requires a '<type 'unicode'>'
TypeError(u"Testcase.__init__() got a '<type 'str'>' for keyword argument 'codename', which requires a '<type 'unicode'>'",)

To me it seems the problem is in the database schema, or something like that. Tried to reinstall but the problem persisted. Can there be a difference in the last version between the import_testcases_from_zip_file script that the init method of the Testcase class?

**Comment by lerks** [comment] 2018-03-14 09:07
This is a duplicate of #885. Closing.

**Closed by lerks** 2018-03-14 09:07 UTC
