### ISSUE TITLE
Worker fails: JobException for more than 10 executions at the same time.

### ISSUE THREAD

**Issue by valiro21** [cms-dev/cms#808] opened 2017-11-24 20:51 UTC
As of now in the recent contests, I get a lot of ```JobException: u'Worker failed.'```, with the actual error being ```SandboxInterfaceException: Failed to initialize sandbox with command: 'isolate' '--cg' '--box-id=25' '--init' (error 2)```.

I presume this happens because of the following line:
https://github.com/cms-dev/cms/blob/1635eddb115c0105b3d0ed323c35c3c6b11c6183/cms/grading/Sandbox.py#L796
As it can be observed, there is a case where we can have a sandbox, let's say with id 11, still running and the ```IsolateSandbox.next_id```, let's say also with value 11. In this case the generated id will be 11. (worker's shard is 0) Thus we try to create a sandbox with the same id as a running one.

Is there any way this can be fixed? In a way this is good because we kinda imposed some kind of limit to the number of parallel executions, but I am thinking of doing this in a way that is more silent without throwing exceptions in the logger or at least detect this case and throw some kind of special Exception. (ex: MaxExecutionsLimitReached).

**Comment by akmohtashami** [comment] 2017-11-24 20:58
Actually, this isn't a result of conflict of a worker with itself since each worker is determined by file cacher service shard uniquely. The problem is that two different workers are trying to get the same shard due to modulo 100. The current implementation can handle up to 30 workers on a single machine. Do you have more?

**Comment by valiro21** [comment] 2017-11-29 07:29
I currently have only 6 workers on the machine.

**Comment by stefano-maggiolo** [comment] 2018-05-15 20:58
This should be fixed either by the increase of available sandboxes, or by calling cleanup before init'ing. Please open another one if you encounter the bug again!

**Closed by stefano-maggiolo** 2018-05-15 20:58 UTC
